### ISSUE TITLE
integration testing: verify that our IPLD CIDs are publishing correctly by testing against Cloudflare

### ISSUE THREAD

**Issue by stellarmagnet** [vulcanize/go-ethereum#76]
The goal of this ticket is to ensure that sufficient integration testing is developed to verify that our IPLD CIDs are publishing in a consistent manner.

We should run the following command against Cloudflare:
`ipfs block put -f {multicodec e.g. 0x90 for header} --mhtype {keccak256}`

The CID generated by publishing to Cloudflare needs to match the ones that are derived via our infrastructure.

**Comment by i-norden** [comment]
Closing this since it is old and unclear now where/why cloudfare fits in. Need to revisit the IPFS stuff in full when it is closer to being a priority/we have someone to focus on it. If we discover this is still relevant, we can revive or track in ops along with the other IPFS issues e.g. https://github.com/vulcanize/ops/issues/79
